name: 21cmLikelihoods
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pip
  - numpy
  - corner
  - tensorflow
  - tensorflow-probability
  - ultranest
  - ipykernel
  - ipywidgets